### ISSUE TITLE
Visual planning of website on paper (add here)

### ISSUE THREAD

**Issue by JonathanBoog** [Filip123/Project-DD1349#10]
Visual planning of website on paper (add here)

**Comment by Filip123** [comment]
<img width="1137" alt="Screenshot 2024-04-25 at 18 41 07" src="https://github.com/Filip123/Project-DD1349/assets/70340989/65a00303-383d-4b4b-b827-e431fbbda24a">

**Comment by Filip123** [comment]
ADD image
